spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
